[package]
name = "azusa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
window = ["raw-window-handle"]

[dependencies]
raw-window-handle = { version = "0.5.0", optional = true }

[dev-dependencies]
winit = "0.28.2"